{% set name = "asciinema" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 32f2c1a046564e030708e596f67e0405425d1eca9d5ec83cd917ef8da06bc423

build:
  skip: True  # [py27 or win]
  number: 1002
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - pip
  run:
    - python

test:
  imports:
    - asciinema
  commands:
    - asciinema --version
    - asciinema rec --help
    - asciinema play --help

about:
  home: https://asciinema.org
  license: GPL-3.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Terminal session recorder and the best companion of asciinema.org.'

  description: |
    asciinema lets you easily record terminal sessions and replay
    them in a terminal as well as in a web browser.
  doc_url: https://asciinema.org/docs
  dev_url: https://github.com/asciinema/asciinema

extra:
  recipe-maintainers:
    - sodre
