{% set name = "asciinema" %}
{% set version = "2.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/asciinema-{{ version }}.tar.gz
  sha256: 828e04c36ba622a7b8f8f912c8f0c1329538b6c7ed1c0d1b131bbbfe3a221707

build:
  number: 0
  noarch: python
  entry_points:
    - asciinema = asciinema.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7

test:
  imports:
    - asciinema
    - asciinema.asciicast
  commands:
    - pip check
    - asciinema --help
  requires:
    - pip

about:
  home: https://asciinema.org
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Terminal session recorder and the best companion of asciinema.org.

  description: |
    asciinema lets you easily record terminal sessions and replay
    them in a terminal as well as in a web browser.
  doc_url: https://asciinema.org/docs
  dev_url: https://github.com/asciinema/asciinema

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
