# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json

schema_version: 1

context:
  version: "3.2.1"

package:
  name: asciinema
  version: ${{ version }}

source:
  url: https://github.com/asciinema/asciinema/archive/refs/tags/v${{ version }}.tar.gz
  sha256: e7e49a09c664a76afc5bc25ca09871eb090bfbe68a2ddbc72750d3cb215d36f1

build:
  number: 0
  # asciinema requires a POSIX terminal and does not support Windows
  skip: win

  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      # build.rs generates man pages and shell completions into ASCIINEMA_GEN_DIR
      - export ASCIINEMA_GEN_DIR=$SRC_DIR/generated
      - cargo auditable install --locked --no-track --bins --root $PREFIX --path .
      - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
      - mkdir -p $PREFIX/share/man/man1 $PREFIX/share/bash-completion/completions $PREFIX/share/zsh/site-functions $PREFIX/share/fish/vendor_completions.d
      - install -m 644 $ASCIINEMA_GEN_DIR/man/*.1 $PREFIX/share/man/man1/
      - install -m 644 $ASCIINEMA_GEN_DIR/completion/asciinema.bash $PREFIX/share/bash-completion/completions/asciinema
      - install -m 644 $ASCIINEMA_GEN_DIR/completion/_asciinema $PREFIX/share/zsh/site-functions/_asciinema
      - install -m 644 $ASCIINEMA_GEN_DIR/completion/asciinema.fish $PREFIX/share/fish/vendor_completions.d/asciinema.fish

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable

tests:
  - script:
      - asciinema --version
      - asciinema --help
  - package_contents:
      bin:
        - asciinema
      files:
        - share/man/man1/asciinema*.1
        - share/bash-completion/completions/asciinema
        - share/zsh/site-functions/_asciinema
        - share/fish/vendor_completions.d/asciinema.fish
      strict: true

about:
  homepage: https://asciinema.org
  summary: Terminal session recorder, streamer, and player
  description: |
    asciinema lets you easily record terminal sessions, replay
    them in a terminal as well as in a web browser, and stream
    them live to viewers.
  license: GPL-3.0-or-later
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  documentation: https://docs.asciinema.org
  repository: https://github.com/asciinema/asciinema

extra:
  recipe-maintainers:
    - sodre
    - ocefpaf
