travis:
  secure:
    BINSTAR_TOKEN: FqozUVLkTWMvg0mfg6X+hiSHD1cRp7A+z94E/Q4+Ia7bs8ePs2qxZxKYd6ioR5d25hoJuoKItTkLcUL/eHNT3+LO4YvLFVyxJEkFh6j1EWUcxUk8msznGXLwFveC9N3DFmrTTIdVDaX6CLbedf4py4xQ3kSc0cOdV2UnnK54rdYQ/17Gb8Xy00eIcaEqe1+WtIla7ZNoISmjNl+KA8MzKhHPluQxiDicc6F8quKkLObsvYQ0vbr+j8yNhwqH/voNI06vzwtKcDBRCm/m+pxGZPvh4ewaJ0Dhfn068muLdO54H9DHTzG4HfVvErvzGxsZdizaXUJigDonutYinnYUjWSatuEuzXl7f9rfDsYGaPUgQ+gJyIlW892jYuuwbfn8hdrissrQtWqFpER4kQR8O1QT9YfbGQNRo7u0RaeNEQ5D5z9WW0Ak3MjsWcwI9hscXUZ4CXovQ2WSYjFcyEdNxuCFwOHqvH5jYOMHvQxUm26GII+6GYkfdPeAFDXKUvealeDbLQqwwEQycs2TZ5+1N0xx5xNEv4vmq8+gy20UTKKapGZFi4XLApIqWc5Ljid6Aj8Xp2lr25VZDfbt0YzaoFctSiEEqup4wAG3Ly454RH/BRC1Z8SrONdrf46vrV2qNa98MRcQMzhmkBGX2bnmUo/zxmKdmOBlZ1kD+YmU29s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
